name: Compile

on:
  push:
    paths:
      - '*.c'
      - '*.h'
      - '.github/workflows/compile.yml'
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download binder.h
        run: curl -O https://raw.githubusercontent.com/s1204IT/CTX_Source/master/kernel-4.14/include/uapi/linux/android/binder.h

      - name: Compile
        run: $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang 2020-0423.c -o 2020-0423 -g -pthread

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: CVE-2020-0423
          path: ./2020-0423
